### ISSUE TITLE
CSS Error when loading the app

### ISSUE THREAD

**Issue by AlexRoig** [vaadin/material-theme-fw8#2]
Hi Team, 

First of all, congratulations for your hard work. This project looks amazing and supper promising. I decided to give it a try but I'm facing a annoying issue. When I launch the app in my browser (also happening with your demo), the app takes around 5 seconds to load.

I've done some research and figured out that the reason why Vaadin wasn't rendering until 5 seconds is because the loading indicator's height is set to 0.

I just set the loading indicator to 1px and now the page loads immediately. I added this snippet on the styles.scss, but not sure what would be the best place to set it. That's why I didn't created a PullRequest and opened an issue instead.

```
.v-loading-indicator {
	height: 1px;
}

```

**Comment by anezthes** [comment]
Thanks! I'll fix that in my next push. :)

**Comment by anezthes** [comment]
Should be fixed now.
