### ISSUE TITLE
Floating TextField's caption/label will not animate with a default value

### ISSUE THREAD

**Issue by AlexRoig** [vaadin/material-theme-fw8#3]
The Floating Text Field will not animate (move up and reduce size) the  caption if the text field has a default value set when creating it. The TextField and the caption will overlap. 
Once you click on it, it'll display properly.

```
MDTextField tf = new MDTextField("Caption", true);
tf.setFloatingLabelEnabled(true);
tf.getField().setValue("Some initial value");
```

Edit: looks like it happens only when it's in a dialog/windnow

**Comment by anezthes** [comment]
Hey Alex,

Does this work?

```
MDTextField tf = new MDTextField("Caption", true);
tf.setFloatingLabelEnabled(true);
tf.setValue("Some initial value");
```

**Comment by AlexRoig** [comment]
Yes, it does! Maybe all the API should go through the MDTextField and make the inner text fields not accessible. Maybe a MDTextField#getValue() would do the trick and avoid confusion.

Thanks!

**Comment by anezthes** [comment]
I've added value change listeners to MDTextField, MDComboBox and and MDTextFieldBox.

Now, even if you do getField().setValue(), the floating label should update.

**Comment by anezthes** [comment]
> Maybe all the API should go through the MDTextField and make the inner text fields not accessible.

Indeed. The idea is to implement HasValue at some point and do exactly that.

**Comment by AlexRoig** [comment]
Works great! Very clever solution
